DROP TABLE IF EXISTS tb_notes CASCADE;
DROP TABLE IF EXISTS tb_passwords CASCADE;
DROP TABLE IF EXISTS tb_users CASCADE;

DROP SEQUENCE IF EXISTS notes_serial CASCADE;
DROP SEQUENCE IF EXISTS passwords_serial CASCADE;
DROP SEQUENCE IF EXISTS users_serial CASCADE;